import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/main.scss';
import Navbar from '@/components/layout/Navbar';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
