import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/main.scss';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

import { getGlobalData } from "@/data/loader";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const globalData = await getGlobalData();
  console.log(await globalData)
  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
        <Footer data={globalData.data.footer}/>
      </body>
    </html>
  );
}
